 SELECT * FROM BORROW
 SELECT * FROM DEPOSIT
 SELECT ACTNO,CNAME,AMOUNT FROM DEPOSIT
 SELECT LOANNO,AMOUNT FROM BORROW
 SELECT * from BORROW where BNAME='ANDHERI'
 SELECT  ACTNO,AMOUNT FROM DEPOSIT WHERE ACTNO='106'
 SELECT  *NAME FROM BORROW WHERE AMOUUNT>5000